version: '3'
services:
  app:
    build: .
    restart: always
    volumes:
      - $PWD:/app
    ports:
      - "5000:5000"
#nfsvolume-flask:
 #   driver: local
  #  driver_opts:
   #   type: "nfs"
    #  o: "addr=192.168.0.96,rw,nfsvers=4"
     # device: ":/nfs-share/docker/easylinux/"
